# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new BetaProduct build to fir"
  lane :BetaProduct do
	buid_app(workspace:"Tool",scheme:"Tool",export_method:"ad-hoc",output_directory:".fastlane/package",configuration:"Release")
	#firim(firm_api_token:"")
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Push a new BetaDebug build to fir"
  lane :pgy do
	#buid_app(workspace:"Tool",scheme:"Tool",export_method:"ad-#hoc",output_directory:".fastlane/package",configuration:"Release")
	#firim(firm_api_token:"")
  gym(
      scheme: “Tool”,
      clean: true,
      workspace: "Tool.xcworkspace",
 	include_bitcode: true,
      output_directory: './pgy',
      output_name: "Tool.ipa",
      export_xcargs: "-allowProvisioningUpdates",
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
